version: '3.9'
services:
  backend:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "192.168.5.97:8000:8000"
    volumes:
      - .:/app


  db:
    image: mysql:8.0.17
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./dbdata:/var/lib/mysql
    ports:
      - "33066:3306"

